use_frameworks!

platform :ios, '13.0'

target 'DeviceInfoCollector_Example' do
  pod 'DeviceInfoCollector', :path => '../'

  target 'DeviceInfoCollector_Tests' do
    inherit! :search_paths

    
  end
end
